# Generated by Django 4.2.8 on 2023-12-17 09:30

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('ORDER_ID', models.CharField(default=myapp.models.generate_order_id, max_length=40, primary_key=True, serialize=False)),
                ('ORDER_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('PLACED_DATE', models.DateTimeField(blank=True, null=True)),
                ('APPROVED_DATE', models.DateTimeField(blank=True, null=True)),
                ('STATUS_ID', models.CharField(blank=True, max_length=40, null=True)),
                ('CURRENCY_UOM_ID', models.CharField(blank=True, max_length=40, null=True)),
                ('PRODUCT_STORE_ID', models.CharField(blank=True, max_length=40, null=True)),
                ('SALES_CHANNEL_ENUM_ID', models.CharField(blank=True, max_length=40, null=True)),
                ('GRAND_TOTAL', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('COMPLETED_DATE', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('PARTY_ID', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('PARTY_TYPE_ENUM_ID', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('PRODUCT_ID', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('PRODUCT_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('DESCRIPTION', models.CharField(blank=True, max_length=4095, null=True)),
                ('CHARGE_SHIPPING', models.CharField(blank=True, max_length=1, null=True)),
                ('RETURNABLE', models.CharField(blank=True, max_length=1, null=True)),
                ('OWNER_PARTY_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.party')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SALUTATION', models.CharField(blank=True, max_length=255, null=True)),
                ('FIRST_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('MIDDLE_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('LAST_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('GENDER', models.CharField(blank=True, max_length=1, null=True)),
                ('BIRTH_DATE', models.DateField(blank=True, null=True)),
                ('MARITAL_STATUS_ENUM_ID', models.CharField(blank=True, max_length=40, null=True)),
                ('EMPLOYMENT_STATUS_ENUM_ID', models.CharField(blank=True, max_length=40, null=True)),
                ('OCCUPATION', models.CharField(blank=True, max_length=255, null=True)),
                ('PARTY_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.party')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDER_PART_SEQ_ID', models.CharField(max_length=40)),
                ('PART_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('STATUS_ID', models.CharField(blank=True, max_length=40, null=True)),
                ('VENDOR_PARTY_ID', models.CharField(blank=True, max_length=40, null=True)),
                ('PART_TOTAL', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('FACILITY_ID', models.CharField(blank=True, max_length=40, null=True)),
                ('SHIPMENT_METHOD_ENUM_ID', models.CharField(blank=True, max_length=40, null=True)),
                ('CUSTOMER_PARTY_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_part_customer', to='myapp.party')),
                ('ORDER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.orderheader')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDER_ITEM_SEQ_ID', models.CharField(max_length=40)),
                ('ORDER_PART_SEQ_ID', models.CharField(blank=True, max_length=40, null=True)),
                ('ITEM_DESCRIPTION', models.CharField(blank=True, max_length=255, null=True)),
                ('QUANTITY', models.DecimalField(blank=True, decimal_places=6, max_digits=26, null=True)),
                ('ITEM_TYPE_ENUM_ID', models.CharField(blank=True, max_length=40, null=True)),
                ('UNIT_AMOUNT', models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True)),
                ('PARENT_ITEM_SEQ_ID', models.CharField(blank=True, max_length=40, null=True)),
                ('ORDER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.orderheader')),
                ('PRODUCT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
